### ISSUE TITLE
Using Netty 4.1.42 Final

### ISSUE THREAD

**Issue by helioguardabaxo** [chanakadinesh/Http2-Server#1]
I tried to use this code, but maven doesn't search the 4.1.5 version.
Server doesn't work after modify dependency to 4.1.42.

May you help me?
Tks

**Comment by chanakadkb** [comment]
Not sure why you can't resolve 4.1.5 version as it still appears in maven repo [1]. 
This quite old and as I remember some method signatures were different
You might find some help from this [2]

[1] [https://mvnrepository.com/artifact/io.netty/netty-all/4.1.5.Final]
[2] [https://github.com/twitter/netty-http2]

**Comment by helioguardabaxo** [comment]
Hi, Chanaka!

My main project is to create a HTTP/2 Server with static files and after to
use  WeightedFairQueueByteDistributor class of Netty to define weight and
stream dependency according to a logic pre-defined.
Do you happen to be willing to build this project as a freelancer?

I tried to run with 4.1.5 on Maven, but doesn't works. It showed this
message:
[image: image.png]

After, I tried to run with 4.1.45 and it ran, but the page does not
complete the load.
 It showed this message:


fev 02, 2020 6:44:36 PM io.netty.handler.logging.LoggingHandler
channelRegistered
INFO: [id: 0x69a58adc] REGISTERED
fev 02, 2020 6:44:36 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0x69a58adc] BIND: 0.0.0.0/0.0.0.0:8888
fev 02, 2020 6:44:36 PM io.netty.handler.logging.LoggingHandler
channelActive
INFO: [id: 0x69a58adc, L:/0:0:0:0:0:0:0:0:8888] ACTIVE
fev 02, 2020 6:44:48 PM io.netty.handler.logging.LoggingHandler channelRead
INFO: [id: 0x69a58adc, L:/0:0:0:0:0:0:0:0:8888] READ: [id: 0xf87a2946, L:/
127.0.0.1:8888 - R:/127.0.0.1:38434]
fev 02, 2020 6:44:48 PM io.netty.handler.logging.LoggingHandler
channelReadComplete
INFO: [id: 0x69a58adc, L:/0:0:0:0:0:0:0:0:8888] READ COMPLETE
fev 02, 2020 6:44:48 PM io.netty.handler.codec.http2.Http2FrameLogger
logSettings
INFO: [id: 0xf87a2946, L:/127.0.0.1:8888 - R:/127.0.0.1:38434] OUTBOUND
SETTINGS: ack=false settings={MAX_HEADER_LIST_SIZE=8192}
fev 02, 2020 6:44:48 PM io.netty.channel.DefaultChannelPipeline
onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail
of the pipeline. It usually means the last handler in the pipeline did not
handle the exception.
io.netty.handler.codec.DecoderException:
javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
at
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert:
bad_certificate
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
at
java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:291)
at
java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:184)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:729)
at
java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:684)
at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:499)
at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:475)
at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:92)
at io.netty.handler.ssl.Java9SslEngine.unwrap(Java9SslEngine.java:141)
at
io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1324)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
at
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
at
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
... 17 more

fev 02, 2020 6:45:05 PM io.netty.handler.logging.LoggingHandler channelRead
INFO: [id: 0x69a58adc, L:/0:0:0:0:0:0:0:0:8888] READ: [id: 0xdd2668ee, L:/
127.0.0.1:8888 - R:/127.0.0.1:38442]
fev 02, 2020 6:45:05 PM io.netty.handler.logging.LoggingHandler
channelReadComplete
INFO: [id: 0x69a58adc, L:/0:0:0:0:0:0:0:0:8888] READ COMPLETE
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logSettings
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] OUTBOUND
SETTINGS: ack=false settings={MAX_HEADER_LIST_SIZE=8192}
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logSettings
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
SETTINGS: ack=false settings={HEADER_TABLE_SIZE=65536,
INITIAL_WINDOW_SIZE=131072, MAX_FRAME_SIZE=16384}
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logSettingsAck
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] OUTBOUND
SETTINGS: ack=true
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logWindowsUpdate
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
WINDOW_UPDATE: streamId=0 windowSizeIncrement=12517377
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logPriority
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PRIORITY: streamId=3 streamDependency=0 weight=201 exclusive=false
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logPriority
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PRIORITY: streamId=5 streamDependency=0 weight=101 exclusive=false
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logPriority
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PRIORITY: streamId=7 streamDependency=0 weight=1 exclusive=false
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logPriority
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PRIORITY: streamId=9 streamDependency=7 weight=1 exclusive=false
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logPriority
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PRIORITY: streamId=11 streamDependency=3 weight=1 exclusive=false
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logPriority
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PRIORITY: streamId=13 streamDependency=0 weight=241 exclusive=false
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logHeaders
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
HEADERS: streamId=15 headers=DefaultHttp2Headers[:method: GET, :path: /,
:authority: localhost:8888, :scheme: https, user-agent: Mozilla/5.0 (X11;
Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0, accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8,
accept-language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3, accept-encoding:
gzip, deflate, br, cookie:
meteor_login_token=wf9XgS7fPTE_ieiaOmAcqQCvEhFwUAoewF0E8-KaRTy,
upgrade-insecure-requests: 1, te: trailers] streamDependency=13 weight=42
exclusive=false padding=0 endStream=true
/
fev 02, 2020 6:45:05 PM io.netty.channel.DefaultChannelPipeline
onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail
of the pipeline. It usually means the last handler in the pipeline did not
handle the exception.
java.lang.NullPointerException
at http2.sample.server.SourceHandler.channelRead(SourceHandler.java:94)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at http2.sample.server.FrameListener.onHeadersRead(FrameListener.java:14)
at
io.netty.handler.codec.http2.Http2FrameListenerDecorator.onHeadersRead(Http2FrameListenerDecorator.java:48)
at
io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onHeadersRead(Http2EmptyDataFrameListener.java:63)
at
io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:373)
at
io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65)
at
io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:457)
at
io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:464)
at
io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
at
io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
at
io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
at
io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
at
io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
at
io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
at
io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
at
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
at
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
at
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
at
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
at
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
at
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:830)

fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logWindowsUpdate
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
WINDOW_UPDATE: streamId=15 windowSizeIncrement=12451840
fev 02, 2020 6:45:05 PM io.netty.handler.codec.http2.Http2FrameLogger
logSettingsAck
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
SETTINGS: ack=true
fev 02, 2020 6:46:04 PM io.netty.handler.codec.http2.Http2FrameLogger
logPing
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] INBOUND
PING: ack=false bytes=0
fev 02, 2020 6:46:04 PM io.netty.handler.codec.http2.Http2FrameLogger
logPingAck
INFO: [id: 0xdd2668ee, L:/127.0.0.1:8888 - R:/127.0.0.1:38442] OUTBOUND
PING: ack=true bytes=0

Thank you for your help!

Em dom., 2 de fev. de 2020 às 03:54, Chanaka Balasooriya <
notifications@github.com> escreveu:

**Comment by chanakadkb** [comment]
Hi Hélio,
It seems an interesting project. 
However, I looked into the particular netty version and as frame.streamId is not available, we need to find the stream from the connection and inject it into the frame in FrameListener class. 
If you describe the requirement in detail, I might be able to help you.
Please contat me via chanakadkb@gmail.com. 

Thanks.

**Comment by chanakadkb** [comment]
Fixed https://github.com/chanakadkb/Http2-Server/commit/ac3351c9c896a14a36ab52b594f0b3b207850323
